### ISSUE TITLE
Text Label Error

### ISSUE THREAD

**Issue by ZongUin** [mahdiyari/dblog#1]
On https://dev.onsteem.com/dashboard there is an error : 

> STEEM: | 37.579 STEEM
> STEEM DOLLARS: | 35.025 SBD
> SEEM POWER: | 1,420.096 STEEM (-1202.128)

We can see "SEEM POWER", but the real text would be "STEEM POWER"

**Comment by mahdiyari** [comment]
Thank you very much:)
